baseURL: https://isomorphic.group/
languageCode: en-us
title: Isomorphic
theme: papermod
paginate: 5

menu:
    main:
        - name: Archive
          url: /archives/
          weight: 10
        - name: Search
          url: /search
          weight: 20
        - name: Tags
          url: /tags
          weight: 30
        - name: About
          url: /about
          weight: 50
        - name: Newsletter
          url: https://forms.gle/n9rR2Jzcv642hsDn9
          weight: 100


params:
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  favicon: "<static/favicon-16x16.png>"
  math: true
  env: production
  ShowFullTextinRSS: true
  homeInfoParams:
    Title: Isomorphic
    Content: Intermittent posts inspired by interesting conversations, thoughts, or
             ruminations that I've had.
  socialIcons: # optional
    - name: "RSS"
      url: "https://isomorphic.group/index.xml"
  showShareButtons: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
